s3:
  bucket: master-data-service
  json-schema-key-prefix: "json-schema/"
  xsd-schema-key-prefix: "xsd-schema/"
  document-key-prefix-date-format: "'capture-document/'yyyy/MM/dd/"

quarkus:
  swagger-ui:
    always-include: true
  opensearch:
    hosts: localhost:9200
  s3:
    endpoint-override: "${S3_ENDPOINT_OVERRIDE:http://127.0.0.1:9100}"
    aws:
      region: "us-east-1"
      path-style-access: true
      credentials:
        type: static
        static-provider:
          access-key-id: "root"
          secret-access-key: "openepcis"
    sync-client:
      type: apache
