quarkus:
  opensearch:
    hosts: openepcis-opensearch:9200
  s3:
    endpoint-override: "${S3_ENDPOINT_OVERRIDE:http://openepcis-minio:9000}"
    aws:
      region: "us-east-1"
      credentials:
        type: static
        static-provider:
          access-key-id: "root"
          secret-access-key: "openepcis"
    sync-client:
      type: apache
  oidc:
    auth-server-url: "${OPENEPCIS_OIDC_AUTH_SERVER_URL:http://openepcis-keycloak:8080/auth/realms/openepcis}"
  smallrye-openapi:
    oidc-open-id-connect-url: "http://openepcis-keycloak:8080/auth/realms/openepcis/.well-known/openid-configuration"
  rest-client:
    keycloak-openepcis-apikey:
      uri: "${KEYCLOAK_OPENEPCIS_APIKEY_URL:http://openepcis-keycloak:8080/auth/realms/openepcis/openepcis-api-key-provider}"

keycloak:
  server-url: "${KEYCLOAK_SERVER_URL:http://openepcis-keycloak:8080/auth}"
